#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

set -e

if [ -z "$OPENSHIFT_DB_HOST" ]
then
echo 1>&2
    echo "Could not find mysql database. Please run:" 1>&2
    echo "rhc app cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
fi

if [ ! -f $OPENSHIFT_DATA_DIR/config/site.php ]
then
    mkdir $OPENSHIFT_DATA_DIR/config
    mkdir -p $OPENSHIFT_DATA_DIR/files/thumbnails
    mkdir -p $OPENSHIFT_DATA_DIR/files/avatars
    mkdir -p $OPENSHIFT_DATA_DIR/files/incoming
    mkdir -p $OPENSHIFT_DATA_DIR/files/tmp
    mkdir -p $OPENSHIFT_DATA_DIR/files/trash
    mkdir $OPENSHIFT_DATA_DIR/packages

    chmod ugo+rwX $OPENSHIFT_DATA_DIR/config
    chmod ugo+rwX $OPENSHIFT_DATA_DIR/files
    chmod ugo+rwX $OPENSHIFT_DATA_DIR/packages
fi

ln -sf $OPENSHIFT_DATA_DIR/config $OPENSHIFT_REPO_DIR/php/config
ln -sf $OPENSHIFT_DATA_DIR/files $OPENSHIFT_REPO_DIR/php/files
ln -sf $OPENSHIFT_DATA_DIR/packages $OPENSHIFT_REPO_DIR/php/packages