#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

set -e

if [ -z "$OPENSHIFT_DB_HOST" ]
then
echo 1>&2
    echo "Could not find mysql database. Please run:" 1>&2
    echo "rhc app cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
fi

if [ ! -f "$OPENSHIFT_DATA_DIRconfig/site.php" ]
then
    mkdir "$OPENSHIFT_DATA_DIRconfig"
    mkdir -p "$OPENSHIFT_DATA_DIRfiles/thumbnails"
    mkdir -p "$OPENSHIFT_DATA_DIRfiles/avatars"
    mkdir -p "$OPENSHIFT_DATA_DIRfiles/incoming"
    mkdir -p "$OPENSHIFT_DATA_DIRfiles/tmp"
    mkdir -p "$OPENSHIFT_DATA_DIRfiles/trash"
    mkdir "$OPENSHIFT_DATA_DIRpackages"

    chmod ugo+rwX "$OPENSHIFT_DATA_DIRconfig"
    chmod ugo+rwX "$OPENSHIFT_DATA_DIRfiles"
    chmod ugo+rwX "$OPENSHIFT_DATA_DIRpackages"
fi

ln -s "$OPENSHIFT_DATA_DIRconfig" "$OPENSHIFT_REPO_DIRphp-5.3/repo/php/config"
ln -s "$OPENSHIFT_DATA_DIRfiles" "$OPENSHIFT_REPO_DIRphp/files"
ln -s "$OPENSHIFT_DATA_DIRpackages" "$OPENSHIFT_REPO_DIRphp/packages"